#! /usr/bin/env php
<?php
// vim: syntax=php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Particular\Ebay\Command\MkdirsCommand;
use Particular\Ebay\Command\MovedirsCommand;
use Particular\Ebay\Command\ResearchCommand;
use Particular\Ebay\Command\SearchCommand;
use Particular\Ebay\Command\SerpCommand;
use Particular\Ebay\Command\ShareCommand;
use Particular\Ebay\Command\TimeApiCommand;
use Particular\Ebay\Command\MergeCommand;

define('COMMAND_DIR', __DIR__);

switch( PHP_OS ) 
{
case 'Darwin': 
	$SYSTEM = 'MAC'; 
	$FIREFOX = '/Applications/Firefox.app/Contents/MacOS/firefox';
	break;
default: 
	$SYSTEM = 'UNIX'; 
	$FIREFOX = 'firefox';
	break;
}

$application = new Application();

$application->add(new MkdirsCommand());
$application->add(new MovedirsCommand());
$application->add(new TimeApiCommand());
$application->add(new SearchCommand());
$application->add(new ShareCommand());
$application->add(new ResearchCommand());
$application->add(new SerpCommand());
$application->add(new MergeCommand());

$application->run();
